// Hayat GIS v3.3.47 - Top filter buttons + detailed What changed
(function(){
  'use strict';
  if(window.__HAYAT_V3347_TOP_FILTER_TOOLS_DETAILED_UPDATES_LOADED) return;
  window.__HAYAT_V3347_TOP_FILTER_TOOLS_DETAILED_UPDATES_LOADED = true;
  var K='HAYAT_UI_LANGUAGE', EN='Hayat_GIS_Training_Guide.pdf', AR='Hayat_GIS_Training_Guide_AR.pdf';
  function q(s,r){return (r||document).querySelector(s)}
  function ar(){return localStorage.getItem(K)==='ar'||document.documentElement.lang==='ar'||document.documentElement.dir==='rtl'}
  function admin(){return /admin\.html/i.test(location.pathname)||!!q('#plotEditModal')||!!q('#exportFullPackageBtn')}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function guide(){return ar()?AR:EN}
  function style(){if(q('#hayat-v3347-style'))return;var s=document.createElement('style');s.id='hayat-v3347-style';s.textContent=[
    '#panel .hayat-v3347-toolbar{display:block!important;width:100%!important;margin:8px 0 12px!important;padding:8px!important;background:rgba(16,33,29,.96)!important;border:1.5px solid #d3ab4e!important;border-radius:14px!important;box-sizing:border-box!important;position:relative!important;z-index:999999!important}',
    '#panel .hayat-v3347-toolbar-title{font-size:11px!important;color:#d3ab4e!important;font-weight:900!important;margin:0 0 6px!important;opacity:.9!important}',
    '#panel .hayat-v3347-toolbar .hayat-v3343-tools{position:static!important;top:auto!important;left:auto!important;right:auto!important;bottom:auto!important;transform:none!important;display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;width:100%!important;max-width:none!important;margin:0!important;padding:0!important;background:transparent!important;border:0!important;box-shadow:none!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important}',
    '#panel .hayat-v3347-toolbar .hayat-v3343-tools button,#panel .hayat-v3347-toolbar .hayat-v3343-tools a{display:flex!important;align-items:center!important;justify-content:center!important;width:100%!important;height:42px!important;min-width:0!important;max-width:none!important;box-sizing:border-box!important;margin:0!important;padding:8px 8px!important;border-radius:10px!important;border:1px solid #d3ab4e!important;background:#10211d!important;color:#d3ab4e!important;text-decoration:none!important;font-size:13px!important;font-weight:900!important;line-height:1.05!important;text-align:center!important;white-space:normal!important;overflow:hidden!important;box-shadow:none!important;cursor:pointer!important}',
    '#panel .hayat-v3347-toolbar .hayat-v3343-tools button:hover,#panel .hayat-v3347-toolbar .hayat-v3343-tools a:hover{background:#1f3f37!important;color:#ffd56b!important}',
    'html.hayat-ar #panel .hayat-v3347-toolbar{direction:rtl!important;text-align:right!important}',
    '#hayat-v3343-panel{z-index:2147483647!important}',
    '#hayat-v3343-panel .hayat-v3347-badge{display:inline-block;background:#10211d;color:#d3ab4e;border-radius:999px;padding:3px 8px;font-size:11px;font-weight:900;margin:2px 4px 2px 0}',
    '#hayat-v3343-panel .hayat-v3347-muted{color:#626262;font-size:12px}',
    '#hayat-v3343-panel .hayat-v3347-card{border:1px solid #ead9a9;background:#fffdf6;border-radius:10px;padding:8px 10px;margin:8px 0}',
    '@media(max-width:820px){#panel .hayat-v3347-toolbar{position:sticky!important;top:0!important;margin:6px 0 10px!important;padding:7px!important;border-radius:12px!important}#panel .hayat-v3347-toolbar .hayat-v3343-tools{gap:6px!important}#panel .hayat-v3347-toolbar .hayat-v3343-tools button,#panel .hayat-v3347-toolbar .hayat-v3343-tools a{height:38px!important;font-size:12px!important;padding:6px 5px!important}body>.hayat-v3343-tools:not(.hayat-v3347-inside-panel){display:none!important}#hayat-v3343-panel{top:64px!important;left:8px!important;right:8px!important;width:auto!important;max-width:none!important;max-height:calc(100dvh - 76px)!important}}',
    '@media(min-width:821px){body>.hayat-v3343-tools:not(.hayat-v3347-inside-panel){display:none!important}}'
  ].join('\n');document.head.appendChild(s)}
  function panel(){var p=q('#hayat-v3343-panel');if(!p){p=document.createElement('div');p.id='hayat-v3343-panel';document.body.appendChild(p)}return p}
  function mk(id,txt,fn){var b=document.createElement('button');b.id=id;b.type='button';b.textContent=txt;b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();fn(e)},true);return b}
  function ensure(){style();var fp=q('#panel')||q('.panel')||q('#filters')||q('.filters'), wrap=q('#hayat-v3347-toolbar');if(!wrap){wrap=document.createElement('div');wrap.id='hayat-v3347-toolbar';wrap.className='hayat-v3347-toolbar';var tt=document.createElement('div');tt.className='hayat-v3347-toolbar-title';wrap.appendChild(tt)}if(fp&&wrap.parentNode!==fp){var after=q('.small-note',fp)||q('h3',fp);if(after&&after.parentNode===fp)after.parentNode.insertBefore(wrap,after.nextSibling);else fp.insertBefore(wrap,fp.firstChild)}else if(!fp&&!wrap.parentNode){document.body.appendChild(wrap)}var ttl=q('.hayat-v3347-toolbar-title',wrap);if(ttl)ttl.textContent=ar()?'أدوات سريعة':'Quick tools';var tools=q('#hayat-v3343-tools')||q('.hayat-v3343-tools');if(!tools){tools=document.createElement('div');tools.id='hayat-v3343-tools';tools.className='hayat-v3343-tools'}tools.classList.add('hayat-v3347-inside-panel');if(tools.parentNode!==wrap)wrap.appendChild(tools);var lang=q('#hayat-v3343-lang');if(!lang){lang=mk('hayat-v3343-lang',ar()?'English':'العربية',function(){localStorage.setItem(K,ar()?'en':'ar');location.reload()});tools.appendChild(lang)}else if(lang.parentNode!==tools)tools.appendChild(lang);lang.textContent=ar()?'English':'العربية';var gd=q('#hayat-v3343-guide');if(!gd){gd=document.createElement('a');gd.id='hayat-v3343-guide';gd.target='_blank';gd.rel='noopener';tools.appendChild(gd)}else if(gd.parentNode!==tools)tools.appendChild(gd);gd.href=guide();gd.textContent=ar()?'دليل التدريب':'Guide';var up=q('#hayat-v3343-updates');if(!up){up=mk('hayat-v3343-updates',ar()?'آخر التحديثات':'What changed',openUpdates);tools.appendChild(up)}else if(up.parentNode!==tools)tools.appendChild(up);up.textContent=ar()?'آخر التحديثات':'What changed';panel()}
  function sec(t,l,ta,la,d,adm){return{t:t,l:l,ta:ta||t,la:la||l,d:d||'',adm:!!adm}}
  function hist(){return[
    sec('Quick buttons moved to filter panel',['Arabic / Guide / What changed are now inside the main filter panel near the top.','The three buttons now have equal width and matching height.','On mobile they stay inside the filter area instead of the phone/browser bottom edge.','The old floating mobile position is suppressed so the map cannot hide the buttons.'],'نقل الأزرار السريعة إلى لوحة الفلاتر',['تم وضع أزرار العربية / دليل التدريب / آخر التحديثات داخل لوحة الفلاتر الرئيسية في الأعلى.','الأزرار الثلاثة أصبحت بنفس العرض والارتفاع.','على الموبايل تبقى الأزرار داخل منطقة الفلاتر بدل أسفل شاشة الهاتف أو المتصفح.','تم إلغاء المكان العائم القديم حتى لا تخفي الخريطة الأزرار.'],'12/09/2026'),
    sec('What changed panel reliability',['Close button now has a stronger handler.','Esc also closes the panel on supported devices.','The update panel appears only when What changed is pressed, so the normal map stays clean.'],'تحسين لوحة آخر التحديثات',['زر الإغلاق أصبح أقوى وأكثر ثباتاً.','زر Esc يغلق اللوحة أيضاً على الأجهزة التي تدعمه.','لوحة التحديثات لا تظهر إلا عند الضغط على آخر التحديثات، لذلك تبقى الخريطة نظيفة.'],'12/09/2026'),
    sec('Language and guide tools',['Arabic / English switch translates common tabs, filter labels, popup labels, option names, and placeholders.','Guide opens the English guide in English mode and the Arabic guide in Arabic mode.','Plot numbers, agent names, phone numbers, prices, coordinates, and PA numbers stay unchanged to avoid data mistakes.'],'أدوات اللغة والدليل',['زر العربية / English يترجم التبويبات والفلاتر وتسميات النوافذ وخيارات القوائم وحقول البحث الشائعة.','الدليل يفتح النسخة الإنجليزية في وضع الإنجليزية والنسخة العربية في وضع العربية.','أرقام القطع وأسماء الوكلاء وأرقام الهواتف والأسعار والإحداثيات وأرقام المخطط تبقى كما هي لتجنب أخطاء البيانات.'],'12/09/2026'),
    sec('Latest map data update',['Inventory records became 495.','Master-plan PA label points remain 2,963.','4 plots were added: 5130989, 5132133, 5134981, and 5135007.','1 old duplicate/reference record was removed: PA4_26.','40 existing plot records were updated from the latest export.','1 master-plan label coordinate was updated: PA4_052.'],'آخر تحديث لبيانات الخريطة',['أصبح عدد سجلات الإنفنتوري 495.','عدد نقاط أرقام المخطط الرئيسي بقي 2,963.','تمت إضافة 4 قطع: 5130989 و 5132133 و 5134981 و 5135007.','تم حذف سجل قديم/مكرر واحد: PA4_26.','تم تحديث 40 سجل قطعة موجودة حسب آخر ملف تصدير.','تم تعديل إحداثيات رقم مخطط واحد: PA4_052.'],'10/09/2026'),
    sec('Added plots details',['5130989 / PA14_223 — Malek Al Masri, 11,625.16 sqft, AED 340/sqft, Red, Single Row, G+1.','5132133 / PA7_126 — Hayat Al Masri, 11,858.83 sqft, AED 350/sqft, Red, Back to Back, construction extension note kept in comments.','5134981 / PA4_026 — Lama Ismail, 10,000.03 sqft, AED 450/sqft, Red, Single Row, G+1.','5135007 / PA4_052 — Issam Al Halabi, 10,000.03 sqft, AED 320/sqft, Red, Back to Back.'],'تفاصيل القطع المضافة',['5130989 / PA14_223 — مالك المصري، 11,625.16 قدم مربع، 340 درهم/قدم، أحمر، صف واحد، G+1.','5132133 / PA7_126 — حياة المصري، 11,858.83 قدم مربع، 350 درهم/قدم، أحمر، ظهر لظهر، وتم حفظ ملاحظة تمديد البناء في التعليقات.','5134981 / PA4_026 — لمى إسماعيل، 10,000.03 قدم مربع، 450 درهم/قدم، أحمر، صف واحد، G+1.','5135007 / PA4_052 — عصام الحلبي، 10,000.03 قدم مربع، 320 درهم/قدم، أحمر، ظهر لظهر.'],'10/09/2026'),
    sec('Updated records details',['Several records received corrected Last Date Updated values from the latest export.','Some second-agent/second-offer fields were cleared where the latest export no longer shows a second offer.','For some plots, the latest export made the former second offer become the main visible offer, such as 5131922, 5135097, and 5135293.','Coordinates were refreshed where the latest export included corrected coordinates.'],'تفاصيل السجلات التي تم تحديثها',['عدة سجلات حصلت على تصحيح في آخر تاريخ تحديث حسب آخر ملف تصدير.','تم حذف بعض حقول الوكيل الثاني/العرض الثاني عندما لم يعد آخر ملف تصدير يحتوي على عرض ثانٍ.','في بعض القطع أصبح العرض الذي كان ثانياً هو العرض الرئيسي الظاهر حسب آخر ملف، مثل 5131922 و 5135097 و 5135293.','تم تحديث الإحداثيات في السجلات التي احتوى ملف التصدير الأخير على إحداثيات مصححة لها.'],'10/09/2026'),
    sec('Search and filters',['Search supports GIS plot number, master-plan plot number, agent name, and mobile number.','Filter tabs include agents, statuses/colors, types, features, phases, GFA, and pricing.','Inside one filter tab, multiple choices work as OR. Between different tabs, filters work together as AND.','All ticks every choice inside the opened filter. Clear removes all ticks inside that filter.'],'البحث والفلاتر',['البحث يدعم رقم قطعة GIS ورقم المخطط الرئيسي واسم الوكيل ورقم الموبايل.','تبويبات الفلترة تشمل الوكلاء والحالات/الألوان والأنواع والمميزات والمراحل و GFA والأسعار.','داخل نفس الفلتر، الاختيارات المتعددة تعمل كـ OR. بين الفلاتر المختلفة، الفلاتر تعمل معاً كـ AND.','زر الكل يحدد كل الخيارات داخل الفلتر المفتوح. زر مسح يلغي التحديد داخل ذلك الفلتر.'],'Filters'),
    sec('Labels and viewing',['Display labels can show GIS plot, master-plan plot, price/sqft, total price, size, agent, GFA, phase, features, and last updated date.','Changing label/detail settings refreshes visible map labels and popup information.','HD master plan and master-plan PA labels can be shown or hidden from map layers.','Agent map remains view-only: agents can search, filter, view, copy details, open guide, and read relevant updates.'],'التسميات والعرض',['تسميات العرض يمكن أن تظهر رقم GIS، رقم المخطط، السعر/قدم، السعر الإجمالي، المساحة، الوكيل، GFA، المرحلة، المميزات، وآخر تاريخ تحديث.','تغيير إعدادات التسميات/التفاصيل يحدث التسميات الظاهرة ومعلومات النافذة المفتوحة.','يمكن إظهار أو إخفاء المخطط الرئيسي HD وأرقام قطع المخطط من طبقات الخريطة.','خريطة الوكيل تبقى للعرض فقط: يمكن للوكيل البحث والفلترة والعرض والنسخ وفتح الدليل وقراءة التحديثات التي تخصه.'],'Display'),
    sec('Copy and sharing tools',['Copy Details and Copy Description remain available for plot sharing.','Copy Selected Details and Copy Selected Description remain available for multiple selected plots.','Description copy keeps useful property details and does not add the old color/status sentence.','Feature information is included in copied descriptions when available.'],'أدوات النسخ والمشاركة',['نسخ التفاصيل ونسخ الوصف ما زالا متاحين لمشاركة معلومات القطعة.','نسخ تفاصيل المحدد ونسخ وصف المحدد متاحان عند تحديد عدة قطع.','نسخ الوصف يحافظ على تفاصيل العقار المفيدة ولا يضيف جملة اللون/الحالة القديمة.','يتم إدخال معلومات المميزات في الوصف المنسوخ عندما تكون متوفرة.'],'Sharing'),
    sec('Admin editing tools',['Admin can add and edit plots: agent, mobile, size, price, type, phase, features, and comments.','Admin can manage second agent / second offer fields.','Last Date Updated is an editable field and can default to today unless manually changed.','GFA allowed can be automatic or manually overridden for special cases.','Admin can move plot coordinates, delete records, export updated map data, and export the full website package.'],'أدوات التعديل الخاصة بالأدمن',['الأدمن يمكنه إضافة وتعديل القطع: الوكيل، الموبايل، المساحة، السعر، النوع، المرحلة، المميزات، والتعليقات.','الأدمن يمكنه إدارة حقول الوكيل الثاني/العرض الثاني.','آخر تاريخ تحديث حقل قابل للتعديل ويمكن أن يأخذ تاريخ اليوم تلقائياً إلا إذا تم تغييره يدوياً.','المساحة البنائية المسموحة GFA يمكن حسابها تلقائياً أو تعديلها يدوياً للحالات الخاصة.','الأدمن يمكنه تحريك إحداثيات القطعة وحذف السجلات وتصدير بيانات الخريطة وتصدير حزمة الموقع كاملة.'],'Admin only',true)
  ]}
  function render(){var p=panel(), A=ar(), isA=admin(), hs=hist().filter(function(x){return isA||!x.adm}), html='';html+='<button type="button" id="hayat-v3343-close">'+(A?'إغلاق':'Close')+'</button><h3>'+(A?'آخر التحديثات':'What changed')+'</h3>';html+='<p class="hayat-v3347-muted">'+esc(A?(isA?'أنت في خريطة الأدمن، لذلك تظهر تحديثات الوكيل بالإضافة إلى أدوات التعديل الخاصة بالأدمن.':'أنت في خريطة الوكيل، لذلك تظهر فقط التحديثات المتعلقة بما يستطيع الوكيل استخدامه: البحث، الفلاتر، التسميات، النسخ، الدليل، والبيانات الظاهرة.'):(isA?'You are on the Admin map, so this shows agent-facing changes plus admin-only editing tools.':'You are on the Agent map, so this shows only changes related to tools agents can actually use: search, filters, labels, copy, guide, and visible map data.'))+'</p>';html+='<div><span class="hayat-v3347-badge">'+(isA?'Admin':'Agent')+'</span><span class="hayat-v3347-badge">'+(A?'مفصل':'Detailed')+'</span></div>';hs.forEach(function(x){html+='<div class="hayat-v3347-card"><h4>'+esc((A?x.ta:x.t)+(x.d?' - '+x.d:''))+'</h4><ul>'; (A?x.la:x.l).forEach(function(li){html+='<li>'+esc(li)+'</li>'}); html+='</ul></div>'});html+='<p class="hayat-v3347-muted">'+esc(A?'ملاحظة: لا يتم عرض تغييرات التعديل الخاصة بالأدمن في خريطة الوكيل حتى لا تربك الوكلاء.':'Note: Admin-only editing changes are hidden on the Agent map so agents only see relevant information.')+'</p>';p.innerHTML=html;var c=q('#hayat-v3343-close',p);if(c)c.onclick=function(e){if(e){e.preventDefault();e.stopPropagation()}close()};return p}
  function openUpdates(){var p=render();p.style.display='block';p.classList.add('open')}
  function close(){var p=q('#hayat-v3343-panel');if(p){p.classList.remove('open');p.style.display='none'}}
  document.addEventListener('click',function(e){var t=e.target;if(!t)return;var u=t.closest&&t.closest('#hayat-v3343-updates');if(u){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();ensure();openUpdates();return false}var c=t.closest&&t.closest('#hayat-v3343-close');if(c){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();close();return false}},true);
  document.addEventListener('keydown',function(e){if(e.key==='Escape')close()},true);
  function boot(){ensure();render();close()}
  [200,700,1400,2500,4200,7000,10000,15000].forEach(function(ms){setTimeout(boot,ms)});
  if(window.MutationObserver){new MutationObserver(function(){clearTimeout(window.__hayat3347timer);window.__hayat3347timer=setTimeout(ensure,120)}).observe(document.documentElement,{childList:true,subtree:true})}
  window.addEventListener('resize',function(){setTimeout(ensure,120)});window.addEventListener('orientationchange',function(){setTimeout(ensure,300)});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
